### ISSUE TITLE
~70% of block requests fail due to strn L1 routing error or timeout

### ISSUE THREAD

**Issue by lidel** [filecoin-saturn/caboose#42]
## Problem

iiuc Rhea produces ~130%  of expected HTTP errors when compared with the old setup (snapshot from bifrost-gw-staging-metrics, see Mean values):

> ![Screenshot 2023-02-23 at 19-56-15 bifrost-gw staging metrics - Bifrost - Dashboards - Grafana](https://user-images.githubusercontent.com/157609/221003733-555248d8-1c57-4c1a-8ade-eda244fa50b1.png)

### Hypothesis 

Look at Mean error rates from Caboose. Success rate of 30%-25% feels painfully inefficient, and may explain end user errors.

> ![2023-02-23-194140_3440x1440_scrot](https://user-images.githubusercontent.com/157609/221002202-a44c382f-41ea-4644-a070-084f492489b2.png)

## Questions / Ideas

- Are there other/better  explanations of 130% of expected errors in the new setup?
- How can we avoid wasting time 75% of time?  (Ideas welcome)
  - Routing errors (404s from L1s) are something Lassie team can investigate 
    - Are these CIDs trully not findable? Last time I checked, IPNI just did not see as much as Accelerated DHT client from Kubo.  Is this still the case?
  - Could Caboose keep a [cache of recently/frequently](https://pkg.go.dev/github.com/hashicorp/golang-lru/v2#TwoQueueCache) failing CIDs and adjust behavior for them? For exampke, 
    - if CID fails due to context timeout, the next time it is requested, instead of timeout of 19s and 3 retries, spend full 60s on a single fetch to get some timeouts over the finish line. 
    - if CID fails multiple times across the pool, add it to a cooldown bucket and return some error that bifrost-gateway could turn into  [429](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429) (Too Many Requests) response with [Retry-After](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After) header matching the cooldown duration.

cc @willscott @aarshkshah1992  for sanity check / ideas how to mitigate

**Comment by willscott** [comment]
* This is an umbrella issue and not just in caboose

For your breakdown:
* IPNI is continuing to work on stabilizing cascadht / accelerated DHT client such that all queries properly return dht results.
    * A fix was applied [this morning](https://github.com/ipni/indexstar/pull/87) that stabilized non-lassie queries.
    * Filed [an issue](https://github.com/ipni/caskadht/issues/28) to track ongoing issue. @masih is DRI for this.
* support for [streaming indexer responses](https://github.com/filecoin-project/lassie/pull/75) should help ttfb from lassie
    * Roll-out of [v0.4.4](https://github.com/filecoin-project/lassie/releases/tag/v0.4.4) will help with responsiveness on cache misses, and make lassie more performant in the current setup.
* the next [saturn l1](https://github.com/filecoin-saturn/L1-node/commit/548b1829652388d536bd20e149e54b5bc7b8e45a) release will transition the 404's to 502's as you've hoped for.

The mitigations you suggest for caboose behavior make sense as well. I'll break those into separate issues

**Comment by willscott** [comment]
Filed the final suggestions as #43 and #44

i think #43 probably makes more sense once we start fetching car files rather than blocks

**Comment by masih** [comment]
About code `0` i.e. timeouts, how can one differentiate between provider lookup timeout and retrieval timeout? @lidel do you have any suggestions?

**Comment by lidel** [comment]
@masih from the perspective of end user talking to ipfs.io both are HTTP 504 (Gateway Timeout).

If we want to bubble up the reason to the end user, then L1 and Caboose should pass the reason in the error response body.

**Comment by lidel** [comment]
Closing as we changed a lot and now working on CAR + Block Fetch backend which needs fine-tuning first:

> ![Screenshot 2023-04-05 at 00-36-34 bifrost-gw staging metrics - Project Rhea - Dashboards - Grafana](https://user-images.githubusercontent.com/157609/229937595-2c6dad27-5891-4a6a-a0d4-f7a509f699dd.png)
