### ISSUE TITLE
Caboose limits CAR responses to 1 minute

### ISSUE THREAD

**Issue by lidel** [filecoin-saturn/caboose#76]
Similar to https://github.com/filecoin-saturn/caboose/issues/75 but time-based:

> ![Screenshot 2023-04-04 at 19-56-54 bifrost-gw staging metrics - Project Rhea - Dashboards - Grafana](https://user-images.githubusercontent.com/157609/229878066-f0bdc2c5-d983-4e28-8af2-40d3e9ce1c02.png)
> ![Screenshot 2023-04-05 at 00-48-46 bifrost-gw staging metrics - Project Rhea - Dashboards - Grafana](https://user-images.githubusercontent.com/157609/229939134-7329afe4-ba56-4a37-96f5-99ff82156013.png)

Looks very suspicious, some ideas:
- could be that metric has a ceiling
- OR  60s timeout from block-based backend is still applied somewhere. Could be caboose, could be client we pass in bifrost-gateway (had no time to investigate).

CAR fetch can take a long time, we may have a ceiling of total time spent on serving a requests at 30m,
but if there is no new bytes arriving for a minute, we should react to that and cut it sooner, and not hang around for 29 minutes.

Some ideas on impl:
- could be a special HTTP transport that we can pass to HTTP client, that tracks how long it was since new bytes were received. 
- OR  we could move this timeout to graph backend in bifrost-gateway, and if we did not receive a new block from the CAR stream for 1 minute, timeout
  - this is elegant, because we can reuse the same block-based timeouts we already have for `?format=raw`

cc @willscott @aarshkshah1992 @aschmahmann

**Comment by aarshkshah1992** [comment]
@lidel 

1. Checked that we are using the correct bucket sizes for car peer failures 
2. That we apply the correct timeout to CAR HTTP reqs
3. That we record the car failure metrics correctly
4. That the Saturn client that Bifrost uses also uses the correct timeout

Is there some other timeout that you are applying to the Graph API ?

**Comment by aarshkshah1992** [comment]
From the Caboose dashboard, per-peer successful CAR fetches can take as long as 10mins

https://protocollabs.grafana.net/d/6g0_YjBVk/bifrost-caboose-staging?from=now-3h&to=now&orgId=1&editPanel=24

**Comment by lidel** [comment]
Indeed, at some point during past 24h  we went beyond 1m cut-off.
We did not deploy new caboose/bifrost-gateway yet, so perhaps there was a timeout in Saturn somewhere then?

> ![Screenshot 2023-04-05 at 19-51-35 bifrost-gw staging metrics - Project Rhea - Dashboards - Grafana](https://user-images.githubusercontent.com/157609/230163212-981fff49-2466-430f-b460-304ce2e8d1b5.png)
